[build-system]
requires = ["setuptools>=45", "wheel", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "agentcomm"
dynamic = ["version", "dependencies"]

[tool.setuptools.dynamic]
version = {attr = "agentcomm.__version__"}
